import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>大反省。</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=''>
        <div className='flex place-content-center'>
          <div className='w-3/4 max-w-screen-md my-12'>
          <p>え～ー...おはようございます(?)</p>
        <p>単刀直入に言うと</p>
        <h1 className='text-4xl'>ごめんなさい。</h1>
        <p>この鯖にも時々アクセスがあって、なんか落ちてるなぁ状態だったので、このページで謝罪させていただきます(?)</p>
        <p>えーっとですね.... 思ったより長引きました...</p>
        <p>今回だいたい15日ぐらいかな...? 落としております原因は、<span className='text-2xl'>引っ越したからです()</span></p>
        <p>あのですね、僕。Misskeyを自宅鯖で建ててたんですが、自宅鯖のデメリットをひしひしひしひしと感じています。</p>
        <hr />
        <p>Q.いつ治るん？</p>
        <p>4月下旬以降ですね( え？長いって？　僕も長いと思ってる(?)</p>
        <p>理由はKDDIの工事が遅いからです((</p>
        <p>治ったら、ソッコーでラズパイつけるんで、、、！</p>
        <p>5月には治ってるので、必ず見に来てね(ニヤ)</p>
        <img src="gomen.png" alt="" />
          </div>
        </div>
      </main>
    </>
  )
}
